### ISSUE TITLE
`clearable` prop nonfunctional in default Select component

### ISSUE THREAD

**Issue by kieferbonk** [City-of-Helsinki/helsinki-design-system#358]
## Describe the bug
For Select component (https://hds.hel.fi/storybook/react/?path=/story/components-dropdowns-select--default), the `clearable` option seems to apply only for multiselect. Changing the cleared prop for a standard select component does not have any effect.

## How to reproduce
1. Go to https://hds.hel.fi/storybook/react/?path=/story/components-dropdowns-select--default
2. Click on 'Controls' > 'Clearable' > 'true'
3. Select an option in the demo select component

## Device information
**Desktop (please complete the following information)**:
>  - OS: macOs
> - Browser Chrome
>  - Version 87

**Comment by ronijaakkola** [comment]
@kieferbonk It hasn't been enabled in HDS since the native HTML select does not allow clearing the field either. HDS also suggests that the default option is set so it is not possible to get the input in a state where nothing is selected.

However, I can see why the current `clearable` prop is confusing since it works in multiselect but not in single select variant. 

In what kind of situation you want to have a clearable single selection dropdown? If there is a good reason for it, I think we can consider enabling it.

**Comment by petrutsi** [comment]
+1 for this problem. Our situation includes multiple dropdowns where default options can't be used, and all the dropdowns use the same pool of options and each option may be selected once only, but the user should be able to change the order of the choices afterwards. E.g. we have dropdowns A and B with choices [1,2]. Let's say in the dropdown A the user picks 1 and in B picks 2. Now the user can't change the selections to A=2 and B=1 anymore as all the options are, and should be, greyed out. 

We've tackled this problem by creating a custom "clear"-button, but now the new Select-component's error message, which is rendered under the dropdown, makes it a little awkward style-wise. All in all, clearable `Single Select`-component would be a perfect solution here. Aso, I too expected it to work like that since `clearable` is part of the common props of the Select-component.

**Comment by ronijaakkola** [comment]
Thanks for the examples of situations where this could be useful. We will add this feature to the default select component.

**Comment by lehtoinen** [comment]
Another +1 here. Our use case is filtering a long list using `Select`. We only want to have one selection active at a time. After making a selection, the user might want to clear that selection to show all the entries again.

For example, see "Toimipaikka" in the screenshot below. Only way to get the full list (not filtered by office) would be to refresh the page. Unless of course we implement something similar to what @petrutsi explained.

![image](https://user-images.githubusercontent.com/6904260/105380613-c3dcde80-5c16-11eb-95a8-0cb6b0c7dc4e.png)

**Comment by VilleMiekkoja** [comment]
This has been fixed in version 1.11.0: https://github.com/City-of-Helsinki/helsinki-design-system/releases/tag/v1.11.0
